import pkg from '@prisma/client';
import dotenv from 'dotenv';
dotenv.config();

const { PrismaClient } = pkg;
const prisma = new PrismaClient();

const jobs = [
  // AI/ML Jobs
  { title: 'Senior ML Engineer', company: 'TechCorp AI', location: 'Remote', salary: '$150k - $200k', type: 'Remote', experience: 'Senior', logo: '🤖', category: 'AI/ML', posted: '2 days ago', applicants: 45, featured: true, description: 'Join our world-class AI team. Build and deploy production ML systems at scale.', aboutCompany: 'TechCorp AI is a leading AI-first company with 200+ ML engineers.', skills: ['Python', 'TensorFlow', 'PyTorch', 'AWS'], responsibilities: ['Design ML models', 'Lead architecture'], requirements: ['5+ years experience', 'Python expertise'], niceToHave: ['PhD in ML'], benefits: ['50k bonus', 'Equity', 'Remote'] },
  { title: 'ML Engineer (NLP)', company: 'LinguaAI', location: 'San Francisco, CA', salary: '$130k - $180k', type: 'Full-time', experience: 'Mid Level', logo: '🧠', category: 'AI/ML', posted: '2 days ago', applicants: 38, featured: false, description: 'Build NLP models for advanced language understanding.', aboutCompany: 'LinguaAI specializes in natural language processing.', skills: ['Python', 'Transformers', 'PyTorch'], responsibilities: ['Build NLP models', 'Create pipelines'], requirements: ['3+ years ML experience'], niceToHave: ['LLM experience'], benefits: ['30k bonus', 'Equity'] },
  { title: 'Computer Vision Engineer', company: 'VisionTech', location: 'Seattle, WA', salary: '$120k - $170k', type: 'Full-time', experience: 'Mid Level', logo: '👁️', category: 'AI/ML', posted: '3 days ago', applicants: 32, featured: false, description: 'Develop computer vision solutions for robotics.', aboutCompany: 'VisionTech develops cutting-edge computer vision.', skills: ['Python', 'OpenCV', 'TensorFlow'], responsibilities: ['Design CV pipelines'], requirements: ['3+ years experience'], niceToHave: ['Robotics'], benefits: ['Competitive salary'] },
  
  // Cloud/DevOps
  { title: 'Cloud Solutions Architect', company: 'CloudSys Inc', location: 'New York, NY', salary: '$140k - $185k', type: 'Full-time', experience: 'Senior', logo: '☁️', category: 'Cloud', posted: '1 day ago', applicants: 62, urgent: true, featured: true, description: 'Design enterprise cloud architectures for Fortune 500.', aboutCompany: 'CloudSys is a top AWS consulting partner.', skills: ['AWS', 'Azure', 'GCP'], responsibilities: ['Architect solutions'], requirements: ['7+ years cloud'], niceToHave: ['AWS cert'], benefits: ['60k bonus', 'Equity'] },
  { title: 'DevOps Engineer', company: 'DeployFlow', location: 'Austin, TX', salary: '$110k - $150k', type: 'Full-time', experience: 'Mid Level', logo: '🐳', category: 'DevOps', posted: '2 days ago', applicants: 42, featured: false, description: 'Build CI/CD pipelines for SaaS platform.', aboutCompany: 'DeployFlow helps startups scale infrastructure.', skills: ['Docker', 'Kubernetes', 'AWS'], responsibilities: ['Build pipelines'], requirements: ['2+ years DevOps'], niceToHave: ['GitOps'], benefits: ['Equity'] },
  { title: 'Infrastructure Engineer', company: 'CloudScale', location: 'San Francisco, CA', salary: '$130k - $170k', type: 'Full-time', experience: 'Senior', logo: '🔧', category: 'DevOps', posted: '1 day ago', applicants: 28, featured: false, description: 'Design infrastructure for millions of users.', aboutCompany: 'CloudScale manages enterprise infrastructure.', skills: ['Terraform', 'Kubernetes', 'Go'], responsibilities: ['Manage infrastructure'], requirements: ['5+ years'], niceToHave: ['Go'], benefits: ['Stock options'] },
  
  // Backend
  { title: 'Senior Backend Engineer', company: 'DataFlow Systems', location: 'Remote', salary: '$140k - $190k', type: 'Remote', experience: 'Senior', logo: '🚀', category: 'Backend', posted: '1 day ago', applicants: 35, featured: true, description: 'Build scalable backend systems processing petabytes.', aboutCompany: 'DataFlow makes real-time data processing.', skills: ['Go', 'Python', 'PostgreSQL'], responsibilities: ['Design APIs'], requirements: ['6+ years'], niceToHave: ['Rust'], benefits: ['Stock options'] },
  { title: 'Backend Engineer (Payments)', company: 'PaymentHub', location: 'New York, NY', salary: '$120k - $160k', type: 'Full-time', experience: 'Mid Level', logo: '💳', category: 'Backend', posted: '2 days ago', applicants: 26, featured: false, description: 'Build payment processing handling billions.', aboutCompany: 'PaymentHub is fintech processing for merchants.', skills: ['Java', 'Python', 'Redis'], responsibilities: ['Build processors'], requirements: ['3+ years'], niceToHave: ['Fintech'], benefits: ['20k bonus'] },
  
  // Frontend
  { title: 'Senior Frontend Engineer', company: 'DesignStudio Pro', location: 'Remote', salary: '$130k - $180k', type: 'Remote', experience: 'Senior', logo: '⚛️', category: 'Frontend', posted: '1 day ago', applicants: 41, featured: true, description: 'Build performant UIs for design tool.', aboutCompany: 'DesignStudio is a leading design platform.', skills: ['React', 'TypeScript', 'WebGL'], responsibilities: ['Design components'], requirements: ['6+ years'], niceToHave: ['WebGL'], benefits: ['Stock options'] },
  { title: 'React Developer', company: 'ShopFlow', location: 'Boston, MA', salary: '$100k - $140k', type: 'Full-time', experience: 'Mid Level', logo: '💻', category: 'Frontend', posted: '2 days ago', applicants: 48, featured: false, description: 'Build e-commerce features with React.', aboutCompany: 'ShopFlow is a rapid-growth e-commerce.', skills: ['React', 'Redux', 'GraphQL'], responsibilities: ['Build UI'], requirements: ['3+ years'], niceToHave: ['Next.js'], benefits: ['12k bonus'] },
  { title: 'Frontend Engineer (Mobile)', company: 'MobileFirst', location: 'San Francisco, CA', salary: '$110k - $150k', type: 'Full-time', experience: 'Mid Level', logo: '📱', category: 'Frontend', posted: '2 days ago', applicants: 35, featured: false, description: 'Build responsive mobile web apps.', aboutCompany: 'MobileFirst specializes in mobile-first.', skills: ['React', 'TypeScript', 'PWA'], responsibilities: ['Build responsive'], requirements: ['3+ years'], niceToHave: [], benefits: ['15k bonus'] },
  
  // Data
  { title: 'Senior Data Engineer', company: 'DataLake Corp', location: 'Remote', salary: '$150k - $200k', type: 'Remote', experience: 'Senior', logo: '📊', category: 'Data', posted: '2 days ago', applicants: 22, featured: true, description: 'Build data infrastructure petabyte-scale.', aboutCompany: 'DataLake provides data for enterprises.', skills: ['Spark', 'Airflow', 'Python'], responsibilities: ['Design data'], requirements: ['6+ years'], niceToHave: ['Delta Lake'], benefits: ['70k bonus'] },
  { title: 'Data Engineer', company: 'AnalyticsHub', location: 'Austin, TX', salary: '$110k - $150k', type: 'Full-time', experience: 'Mid Level', logo: '📈', category: 'Data', posted: '1 day ago', applicants: 29, featured: false, description: 'Build real-time data pipelines.', aboutCompany: 'AnalyticsHub provides real-time analytics.', skills: ['Python', 'SQL', 'Kafka'], responsibilities: ['Build pipelines'], requirements: ['2+ years'], niceToHave: ['Spark'], benefits: ['18k bonus'] },
];

const courses = [
  // AI/ML Courses
  { title: 'Advanced Machine Learning with Python', instructor: 'Dr. Sarah Chen', instructorBio: 'PhD from MIT, ex-Google Brain, 15+ years ML', instructorAvatar: '👩‍🔬', rating: 4.9, reviews: 12450, students: 45200, duration: '8 weeks', level: 'Advanced', image: '🤖', price: '149', originalPrice: '299', bestseller: true, skills: ['Python', 'TensorFlow', 'Neural Networks'], category: 'AI/ML', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-violet-500 to-purple-600', description: 'Master advanced ML with hands-on projects building production systems.', whatYouLearn: ['Build neural networks', 'Deploy models to production', 'Optimize ML pipelines'], prerequisites: ['Python intermediate', 'Math basics'], modules: [] },
  { title: 'Natural Language Processing Masterclass', instructor: 'Prof. James Wilson', instructorBio: 'Ex-OpenAI, 12 years NLP research', instructorAvatar: '👨‍🏫', rating: 4.8, reviews: 8920, students: 32100, duration: '10 weeks', level: 'Advanced', image: '🧠', price: '179', originalPrice: '349', bestseller: true, skills: ['Transformers', 'BERT', 'GPT', 'PyTorch'], category: 'AI/ML', language: 'English', lastUpdated: 'February 2026', certificate: true, color: 'from-blue-500 to-cyan-500', description: 'Become NLP expert. Learn transformers, fine-tune LLMs, deploy at scale.', whatYouLearn: ['Transformers', 'Fine-tune BERT', 'Question answering'], prerequisites: ['Deep learning basics'], modules: [] },
  
  // Cloud/DevOps Courses
  { title: 'AWS Solutions Architect Professional', instructor: 'Mark Johnson', instructorBio: 'AWS Certified Solutions Architect, 10+ years cloud', instructorAvatar: '👨‍💼', rating: 4.7, reviews: 15600, students: 78900, duration: '12 weeks', level: 'Advanced', image: '☁️', price: '129', originalPrice: '249', bestseller: true, skills: ['AWS', 'Architecture', 'Security'], category: 'Cloud', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-orange-500 to-red-500', description: 'Master AWS architecture for enterprise-scale applications.', whatYouLearn: ['Design scalable AWS', 'High availability', 'Cost optimization'], prerequisites: ['AWS fundamentals'], modules: [] },
  { title: 'Kubernetes for DevOps Engineers', instructor: 'Emily Rodriguez', instructorBio: 'Ex-Google, Kubernetes contributor, 8+ years DevOps', instructorAvatar: '👩‍💻', rating: 4.8, reviews: 9200, students: 34500, duration: '8 weeks', level: 'Intermediate', image: '🐳', price: '99', originalPrice: '199', bestseller: true, skills: ['Kubernetes', 'Docker', 'Helm', 'GitOps'], category: 'DevOps', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-blue-600 to-blue-400', description: 'Master Kubernetes from basics to advanced production patterns.', whatYouLearn: ['Deploy applications', 'Scale clusters', 'Monitor systems'], prerequisites: ['Docker basics'], modules: [] },
  
  // Web Development Courses
  { title: 'React: Build Modern Web Apps', instructor: 'Lisa Anderson', instructorBio: 'React Core Contributor, 10+ years frontend', instructorAvatar: '👩‍🔬', rating: 4.9, reviews: 28560, students: 120340, duration: '6 weeks', level: 'Intermediate', image: '⚛️', price: '89', originalPrice: '199', bestseller: true, skills: ['React', 'JavaScript', 'TypeScript', 'Redux'], category: 'Frontend', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-cyan-500 to-blue-500', description: 'Learn React by building real-world applications from hooks to patterns.', whatYouLearn: ['React fundamentals', 'Hooks deep dive', 'Performance optimization'], prerequisites: ['JavaScript ES6+'], modules: [] },
  { title: 'Full Stack Development with MERN', instructor: 'David Lee', instructorBio: 'Full stack engineer, startup founder', instructorAvatar: '👨‍💼', rating: 4.7, reviews: 12340, students: 45670, duration: '10 weeks', level: 'Intermediate', image: '🚀', price: '119', originalPrice: '259', bestseller: false, skills: ['React', 'Node.js', 'MongoDB', 'Express'], category: 'Backend', language: 'English', lastUpdated: 'February 2026', certificate: true, color: 'from-green-500 to-emerald-500', description: 'Build complete web applications with MongoDB, Express, React, Node.js.', whatYouLearn: ['RESTful APIs', 'React frontend', 'Database design'], prerequisites: ['JavaScript'], modules: [] },
  
  // Data Science Courses
  { title: 'Data Science with Python', instructor: 'Dr. Michael Wong', instructorBio: 'Data scientist, Kaggle Master, 8+ years', instructorAvatar: '👨‍🔬', rating: 4.8, reviews: 16720, students: 67200, duration: '9 weeks', level: 'Intermediate', image: '📊', price: '109', originalPrice: '229', bestseller: true, skills: ['Python', 'Pandas', 'Scikit-learn', 'Statistics'], category: 'Data Science', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-pink-500 to-rose-500', description: 'Master data science from exploration to ML models and visualization.', whatYouLearn: ['Data cleaning', 'Statistical analysis', 'ML models'], prerequisites: ['Python basics'], modules: [] },
  { title: 'SQL for Data Analysis', instructor: 'Robert Kim', instructorBio: 'Database architect, 12+ years data', instructorAvatar: '👨‍💼', rating: 4.9, reviews: 22100, students: 89340, duration: '4 weeks', level: 'Beginner', image: '🗄️', price: '59', originalPrice: '129', bestseller: true, skills: ['SQL', 'Database Design', 'Query Optimization'], category: 'Databases', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-indigo-500 to-purple-500', description: 'Master SQL for data analysis and efficient queries.', whatYouLearn: ['SELECT queries', 'JOINs and aggregations', 'Window functions'], prerequisites: [], modules: [] },
];

const assessments = [
  // Programming Assessments
  { title: 'Python Programming', category: 'Programming', difficulty: 'Intermediate', duration: 45, badge: '🐍', skills: ['Python', 'OOP', 'Data Structures'], attempts: 12450, avgScore: 78, description: 'Test your Python programming knowledge with 20+ questions.', color: 'from-blue-500 to-cyan-500', questions: [{ id: 1, question: 'What is the output of: print(type([]))?', options: ["<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'dict'>"], correct: 0, explanation: 'Empty brackets [] create a list.' }, { id: 2, question: 'What keyword defines a function?', options: ['function', 'def', 'fun', 'define'], correct: 1, explanation: 'Use def to define Python functions.' }, { id: 3, question: 'How do you access the last element?', options: ['x[0]', 'x[-1]', 'x[len]', 'x.last'], correct: 1, explanation: 'x[-1] accesses the last element.' }, { id: 4, question: 'How do you create a dictionary?', options: ['{}', '[]', '()', '<>'], correct: 0, explanation: '{} creates a dictionary.' }] },
  { title: 'JavaScript Fundamentals', category: 'Programming', difficulty: 'Beginner', duration: 40, badge: '✨', skills: ['JavaScript', 'ES6', 'DOM'], attempts: 15600, avgScore: 82, description: 'Test your JavaScript knowledge covering basics and modern features.', color: 'from-yellow-400 to-orange-500', questions: [{ id: 1, question: 'How do you declare a variable?', options: ['v x = 5', 'var x = 5', 'variable x = 5', 'let x = 5'], correct: 1, explanation: 'var, let, or const declare variables.' }, { id: 2, question: "What does 'typeof []' return?", options: ['array', 'object', 'list', 'collection'], correct: 1, explanation: 'Arrays are objects in JavaScript.' }, { id: 3, question: 'What is 1 + "1" in JS?', options: ['2', '"11"', 'error', 'NaN'], correct: 1, explanation: 'Type coercion: number + string = string.' }, { id: 4, question: 'Which removes last element?', options: ['shift()', 'pop()', 'remove()', 'delete()'], correct: 1, explanation: 'pop() removes and returns last element.' }] },
  
  // Database Assessment
  { title: 'SQL Fundamentals', category: 'Databases', difficulty: 'Beginner', duration: 35, badge: '🗄️', skills: ['SQL', 'Databases', 'Queries'], attempts: 18900, avgScore: 85, description: 'Test your SQL knowledge with practical query questions.', color: 'from-indigo-500 to-purple-500', questions: [{ id: 1, question: 'Which keyword selects data?', options: ['FETCH', 'SELECT', 'GET', 'RETRIEVE'], correct: 1, explanation: 'SELECT retrieves data from database.' }, { id: 2, question: 'How to filter WHERE age > 30?', options: ['SELECT * WHERE', 'SELECT * FROM users WHERE age > 30', 'WHERE users age > 30', 'FIND WHERE'], correct: 1, explanation: 'Use FROM then WHERE clause.' }, { id: 3, question: 'What does DISTINCT do?', options: ['Removes duplicates', 'Sorts data', 'Groups rows', 'Counts rows'], correct: 0, explanation: 'DISTINCT removes duplicate rows.' }, { id: 4, question: 'How to join tables?', options: ['SELECT t1+t2', 'SELECT FROM t1 JOIN t2', 'MERGE t1,t2', 'COMBINE'], correct: 1, explanation: 'Use JOIN to combine tables.' }] },
  
  // Frontend Assessment
  { title: 'React & Frontend', category: 'Frontend', difficulty: 'Intermediate', duration: 50, badge: '⚛️', skills: ['React', 'JavaScript', 'JSX'], attempts: 10200, avgScore: 76, description: 'Test your React knowledge and component patterns.', color: 'from-cyan-500 to-blue-500', questions: [{ id: 1, question: 'What is JSX?', options: ['Java XML', 'JavaScript XML', 'JSON Extra', 'Syntax ext'], correct: 1, explanation: 'JSX is JavaScript XML syntax for React.' }, { id: 2, question: 'How to pass props?', options: ['<C props={d} />', '<C data />', 'C(d)', 'C.props=d'], correct: 0, explanation: 'Props passed as JSX attributes.' }, { id: 3, question: 'What hook replaces componentDidMount?', options: ['useState', 'useEffect', 'useContext', 'useReducer'], correct: 1, explanation: 'useEffect replaces lifecycle hooks.' }, { id: 4, question: 'When use useCallback?', options: ['Always', 'Pass function to children', 'Every fn', 'Never'], correct: 1, explanation: 'Memoize functions for performance.' }] },
  
  // Cloud Assessment
  { title: 'AWS Fundamentals', category: 'Cloud', difficulty: 'Beginner', duration: 55, badge: '☁️', skills: ['AWS', 'Cloud', 'EC2', 'S3'], attempts: 22400, avgScore: 79, description: 'Test your AWS cloud concepts and services knowledge.', color: 'from-orange-500 to-yellow-500', questions: [{ id: 1, question: 'S3 stands for?', options: ['Service Storage', 'Simple Storage Service', 'Server Storage', 'Secure Storage'], correct: 1, explanation: 'S3 = Simple Storage Service.' }, { id: 2, question: 'What is Availability Zone?', options: ['Region', 'Data center', 'Billing zone', 'Network'], correct: 1, explanation: 'AZ is physical data center.' }, { id: 3, question: 'High availability needs?', options: ['Single instance', 'Multiple AZs', 'RDS', 'VPC'], correct: 1, explanation: 'Distribute across multiple AZs.' }, { id: 4, question: 'IAM means?', options: ['Inter AWS', 'Identity Access Management', 'Admin Module', 'Access Method'], correct: 1, explanation: 'IAM manages access and permissions.' }] },
  
  // DevOps Assessment
  { title: 'Docker & Containers', category: 'DevOps', difficulty: 'Intermediate', duration: 45, badge: '🐳', skills: ['Docker', 'Containers', 'Kubernetes'], attempts: 8900, avgScore: 81, description: 'Test your containerization and Docker knowledge.', color: 'from-blue-600 to-cyan-400', questions: [{ id: 1, question: 'Container is a?', options: ['VM type', 'Lightweight process', 'Storage device', 'Network'], correct: 1, explanation: 'Containers are lightweight processes.' }, { id: 2, question: 'Dockerfile contains?', options: ['Files list', 'Build instructions', 'Security rules', 'Repository'], correct: 1, explanation: 'Dockerfile has build instructions.' }, { id: 3, question: 'Run docker container?', options: ['docker create', 'docker run', 'docker start', 'docker exec'], correct: 1, explanation: 'docker run creates and starts.' }, { id: 4, question: 'Image vs Container?', options: ['Same', 'Template vs instance', 'Opposite', 'Related'], correct: 1, explanation: 'Image is blueprint, container is running.' }] },
  
  // ML Assessment
  { title: 'Machine Learning Basics', category: 'AI/ML', difficulty: 'Intermediate', duration: 50, badge: '🤖', skills: ['ML', 'Python', 'Scikit-learn'], attempts: 9450, avgScore: 74, description: 'Test your machine learning concepts and algorithms.', color: 'from-purple-500 to-pink-500', questions: [{ id: 1, question: 'Supervised learning uses?', options: ['No labels', 'Labeled data', 'Unsupervised', 'Self-taught'], correct: 1, explanation: 'Supervised uses labeled training data.' }, { id: 2, question: 'What is overfitting?', options: ['Too much data', 'Memorizes training', 'Few features', 'Samples'], correct: 1, explanation: 'Model learns noise, poor on new data.' }, { id: 3, question: 'Train-test split ratio?', options: ['50-50', '70-30 or 80-20', 'All train', 'Random'], correct: 1, explanation: 'Typical: 70-30 or 80-20 split.' }, { id: 4, question: 'Cross-validation purpose?', options: ['Validate code', 'Better estimate', 'Validate data', 'Train faster'], correct: 1, explanation: 'Provides robust performance estimate.' }] },
  
  // System Design Assessment
  { title: 'System Design Fundamentals', category: 'Architecture', difficulty: 'Advanced', duration: 70, badge: '🏗️', skills: ['System Design', 'Scalability', 'Architecture'], attempts: 4500, avgScore: 65, description: 'Test your system design and scalability knowledge.', color: 'from-slate-600 to-gray-700', questions: [{ id: 1, question: 'Horizontal scaling is?', options: ['More power', 'More servers', 'Faster CPU', 'More RAM'], correct: 1, explanation: 'Horizontal = add more servers.' }, { id: 2, question: 'Eventual consistency?', options: ['Always consistent', 'Eventually consistent', 'Consistency check', 'Always sync'], correct: 1, explanation: 'Data eventually becomes consistent.' }, { id: 3, question: 'Load balancer does?', options: ['Balance weight', 'Distribute traffic', 'Balance code', 'DB tool'], correct: 1, explanation: 'Distributes to multiple servers.' }, { id: 4, question: 'CAP theorem?', options: ['Capacity', 'Consistency, Availability, Partition', 'Network', 'Data'], correct: 1, explanation: 'Pick 2 of 3: Consistency, Availability, Tolerance.' }] },
];

const importData = async () => {
  try {
    console.log('Connecting to database...');
    
    await prisma.assessment.deleteMany();
    await prisma.course.deleteMany();
    await prisma.job.deleteMany();
    
    console.log('Inserting data...');
    await prisma.job.createMany({ data: jobs });
    console.log(`Inserted ${jobs.length} jobs`);
    
    await prisma.course.createMany({ data: courses });
    console.log(`Inserted ${courses.length} courses`);
    
    await prisma.assessment.createMany({ data: assessments });
    console.log(`Inserted ${assessments.length} assessments`);

    console.log('✓ Database seeded with proper emojis and icons!');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
};

importData();
