import pkg from '@prisma/client';
import dotenv from 'dotenv';
dotenv.config();

const { PrismaClient } = pkg;
const prisma = new PrismaClient();

const jobs = [
  { title: 'Senior ML Engineer', company: 'TechCorp AI', location: 'Remote', salary: '$150k - $200k', type: 'Remote', experience: 'Senior', logo: 'R', category: 'AI/ML', posted: '2 days ago', applicants: 45, featured: true, description: 'Join our world-class AI team. Build and deploy production ML systems at scale.', aboutCompany: 'TechCorp AI is a leading AI-first company with 200+ ML engineers.', skills: ['Python', 'TensorFlow', 'PyTorch', 'AWS'], responsibilities: ['Design ML models', 'Lead architecture'], requirements: ['5+ years experience', 'Python expertise'], niceToHave: ['PhD in ML'], benefits: ['50k bonus', 'Equity', 'Remote'] },
  { title: 'Cloud Solutions Architect', company: 'CloudSys Inc', location: 'New York, NY', salary: '$140k - $185k', type: 'Full-time', experience: 'Senior', logo: 'C', category: 'Cloud', posted: '1 day ago', applicants: 62, urgent: true, featured: false, description: 'Design enterprise cloud architectures for Fortune 500 companies.', aboutCompany: 'CloudSys Inc is a top AWS consulting partner.', skills: ['AWS', 'Azure', 'GCP'], responsibilities: ['Architect solutions', 'Lead engagements'], requirements: ['7+ years cloud experience'], niceToHave: ['AWS certification'], benefits: ['60k bonus', 'Equity', 'Travel'] },
  { title: 'React Frontend Engineer', company: 'WebFlow Inc', location: 'Denver, CO', salary: '$100k - $140k', type: 'Full-time', experience: 'Mid Level', logo: 'R', category: 'Frontend', posted: '3 days ago', applicants: 28, featured: false, description: 'Build responsive web applications with React and modern JavaScript.', aboutCompany: 'WebFlow Inc is a fast-growing SaaS company.', skills: ['React', 'TypeScript', 'Tailwind'], responsibilities: ['Build UI components', 'Optimize performance'], requirements: ['3+ years React experience'], niceToHave: ['Next.js'], benefits: ['20k bonus', 'Flexible hours'] },
  { title: 'Python Backend Engineer', company: 'DataFlow Systems', location: 'Remote', salary: '$130k - $170k', type: 'Remote', experience: 'Senior', logo: 'P', category: 'Backend', posted: '1 day ago', applicants: 35, featured: false, description: 'Build scalable backend systems. Design APIs and data pipelines.', aboutCompany: 'DataFlow Systems processes petabytes of data.', skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis'], responsibilities: ['Design APIs', 'Optimize performance'], requirements: ['5+ years backend experience'], niceToHave: ['Rust knowledge'], benefits: ['Stock options', 'Learning budget'] },
  { title: 'DevOps Engineer', company: 'DeployFlow', location: 'Austin, TX', salary: '$110k - $150k', type: 'Full-time', experience: 'Mid Level', logo: 'D', category: 'DevOps', posted: '2 days ago', applicants: 42, featured: false, description: 'Build and maintain CI/CD pipelines. Deploy containerized applications.', aboutCompany: 'DeployFlow helps startups scale infrastructure.', skills: ['Docker', 'Kubernetes', 'Jenkins', 'AWS'], responsibilities: ['Build CI/CD pipelines', 'Manage infrastructure'], requirements: ['2+ years DevOps experience'], niceToHave: ['GitOps'], benefits: ['Equity', 'Flexible hours'] },
  { title: 'Data Scientist', company: 'AnalyticsPro', location: 'San Francisco, CA', salary: '$120k - $160k', type: 'Full-time', experience: 'Mid Level', logo: 'A', category: 'Data Science', posted: '2 days ago', applicants: 31, featured: true, description: 'Build ML models for real-time analytics. Work with big data frameworks.', aboutCompany: 'AnalyticsPro provides real-time analytics for Fortune 500.', skills: ['Python', 'Scikit-learn', 'Spark', 'SQL'], responsibilities: ['Build models', 'Optimize queries'], requirements: ['3+ years data science'], niceToHave: ['Spark expertise'], benefits: ['25k bonus', 'Gym membership'] },
  { title: 'Security Engineer', company: 'CyberShield', location: 'Remote', salary: '$140k - $190k', type: 'Remote', experience: 'Senior', logo: 'S', category: 'Security', posted: '3 days ago', applicants: 18, featured: false, description: 'Lead security at a cybersecurity company. Design threat detection systems.', aboutCompany: 'CyberShield protects Fortune 500 companies.', skills: ['Security', 'Python', 'Go', 'Kubernetes'], responsibilities: ['Design security', 'Threat analysis'], requirements: ['7+ years security'], niceToHave: ['CISSP'], benefits: ['80k bonus', 'Stock options'] },
  { title: 'Full Stack Developer', company: 'StartupHub', location: 'Boston, MA', salary: '$95k - $135k', type: 'Full-time', experience: 'Entry Level', logo: 'S', category: 'Full Stack', posted: '1 day ago', applicants: 55, featured: false, description: 'Build full-stack features for a growing startup. Work with modern tech.', aboutCompany: 'StartupHub is a venture-backed startup platform.', skills: ['Node.js', 'React', 'MongoDB', 'AWS'], responsibilities: ['Build features', 'Write tests'], requirements: ['1+ year experience', 'JavaScript'], niceToHave: ['TypeScript'], benefits: ['10k bonus', 'Equity', 'Flexible'] },
  { title: 'Database Administrator', company: 'DataCore', location: 'Chicago, IL', salary: '$105k - $145k', type: 'Full-time', experience: 'Mid Level', logo: 'D', category: 'Database', posted: '2 days ago', applicants: 22, featured: false, description: 'Manage and optimize databases. Ensure 99.99% uptime.', aboutCompany: 'DataCore manages databases for tech companies.', skills: ['PostgreSQL', 'MySQL', 'Monitoring', 'Linux'], responsibilities: ['Optimize databases', 'Manage backups'], requirements: ['4+ years DBA experience'], niceToHave: ['Cloud databases'], benefits: ['Continuous learning'] },
  { title: 'Mobile App Developer', company: 'MobileFirst', location: 'San Francisco, CA', salary: '$115k - $155k', type: 'Full-time', experience: 'Mid Level', logo: 'M', category: 'Mobile', posted: '2 days ago', applicants: 38, featured: false, description: 'Build iOS/Android apps for millions of users.', aboutCompany: 'MobileFirst is a mobile-first company.', skills: ['Swift', 'Kotlin', 'React Native'], responsibilities: ['Build apps', 'Optimize performance'], requirements: ['3+ years mobile'], niceToHave: [], benefits: ['15k bonus'] },
];

const courses = [
  { title: 'Advanced ML with Python', instructor: 'Dr. Sarah Chen', instructorBio: 'PhD from MIT, 15+ years ML', instructorAvatar: 'S', rating: 4.9, reviews: 12450, students: 45200, duration: '8 weeks', level: 'Advanced', image: 'M', price: '149', originalPrice: '299', bestseller: true, skills: ['Python', 'TensorFlow'], category: 'AI/ML', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-violet-500 to-purple-600', description: 'Master ML with hands-on projects.', whatYouLearn: ['Build neural networks', 'Deploy models'], prerequisites: ['Python basics'], modules: [] },
  { title: 'AWS Solutions Architect', instructor: 'Mark Johnson', instructorBio: 'AWS certified, 10+ years cloud', instructorAvatar: 'M', rating: 4.7, reviews: 15600, students: 78900, duration: '12 weeks', level: 'Advanced', image: 'A', price: '129', originalPrice: '249', bestseller: true, skills: ['AWS', 'Architecture'], category: 'Cloud', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-orange-500 to-red-500', description: 'Master AWS architecture design.', whatYouLearn: ['Design scalable solutions', 'Implement HA'], prerequisites: ['AWS basics'], modules: [] },
  { title: 'React Masterclass', instructor: 'Lisa Anderson', instructorBio: 'React expert, 10+ years frontend', instructorAvatar: 'L', rating: 4.9, reviews: 28560, students: 120340, duration: '6 weeks', level: 'Intermediate', image: 'R', price: '89', originalPrice: '199', bestseller: true, skills: ['React', 'JavaScript'], category: 'Frontend', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-cyan-500 to-blue-500', description: 'Learn React from basics to advanced.', whatYouLearn: ['Build components', 'Manage state'], prerequisites: ['JavaScript'], modules: [] },
  { title: 'Kubernetes for DevOps', instructor: 'Emily Rodriguez', instructorBio: 'Ex-Google, K8s expert', instructorAvatar: 'E', rating: 4.8, reviews: 9200, students: 34500, duration: '8 weeks', level: 'Intermediate', image: 'K', price: '99', originalPrice: '199', bestseller: true, skills: ['Kubernetes', 'Docker'], category: 'DevOps', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-blue-600 to-blue-400', description: 'Master Kubernetes deployment.', whatYouLearn: ['Deploy apps', 'Scale clusters'], prerequisites: ['Docker basics'], modules: [] },
  { title: 'Data Science with Python', instructor: 'Dr. Michael Wong', instructorBio: 'Kaggle Master, 8 years DS', instructorAvatar: 'M', rating: 4.8, reviews: 16720, students: 67200, duration: '9 weeks', level: 'Intermediate', image: 'D', price: '109', originalPrice: '229', bestseller: true, skills: ['Python', 'Pandas'], category: 'Data Science', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-pink-500 to-rose-500', description: 'Learn data science fundamentals.', whatYouLearn: ['Clean data', 'Build models'], prerequisites: ['Python'], modules: [] },
  { title: 'SQL Mastery', instructor: 'Robert Kim', instructorBio: 'DB architect, 12 years', instructorAvatar: 'R', rating: 4.9, reviews: 22100, students: 89340, duration: '4 weeks', level: 'Beginner', image: 'S', price: '59', originalPrice: '129', bestseller: true, skills: ['SQL', 'Databases'], category: 'Databases', language: 'English', lastUpdated: 'March 2026', certificate: true, color: 'from-indigo-500 to-purple-500', description: 'Master SQL for data analysis.', whatYouLearn: ['Write queries', 'Design schemas'], prerequisites: [], modules: [] },
  { title: 'Node.js API Development', instructor: 'David Lee', instructorBio: 'Full-stack engineer', instructorAvatar: 'D', rating: 4.7, reviews: 12340, students: 45670, duration: '10 weeks', level: 'Intermediate', image: 'N', price: '119', originalPrice: '259', bestseller: false, skills: ['Node.js', 'Express'], category: 'Backend', language: 'English', lastUpdated: 'February 2026', certificate: true, color: 'from-green-500 to-emerald-500', description: 'Build powerful APIs with Node.js.', whatYouLearn: ['Create REST APIs', 'Handle databases'], prerequisites: ['JavaScript'], modules: [] },
];

const assessments = [
  { title: 'Python Basics', category: 'Programming', difficulty: 'Beginner', duration: 30, badge: 'P', skills: ['Python'], attempts: 8900, avgScore: 82, description: 'Test your Python knowledge.', color: 'from-blue-500 to-cyan-500', questions: [{ id: 1, question: 'What prints list type?', options: ["<class 'list'>", "<class 'array'>", 'list', 'array'], correct: 0, explanation: 'type([]) returns list class.' }, { id: 2, question: 'Function keyword?', options: ['function', 'def', 'fun', 'define'], correct: 1, explanation: 'Use def to define functions.' }, { id: 3, question: 'Last element access?', options: ['x[0]', 'x[-1]', 'x[len]', 'x.last'], correct: 1, explanation: 'x[-1] gets the last element.' }, { id: 4, question: 'Create dict?', options: ['dict = []', 'dict = {}', 'dict = ()', 'dict = <>'], correct: 1, explanation: '{} creates a dictionary.' }] },
  { title: 'JavaScript Basics', category: 'Programming', difficulty: 'Beginner', duration: 35, badge: 'J', skills: ['JavaScript'], attempts: 11200, avgScore: 79, description: 'Test your JavaScript knowledge.', color: 'from-yellow-400 to-orange-500', questions: [{ id: 1, question: 'Declare variable?', options: ['v x = 5', 'var x = 5', 'variable x = 5', 'let x = 5'], correct: 1, explanation: 'var, let, or const declare variables.' }, { id: 2, question: 'Array type?', options: ['array', 'object', 'list', 'collection'], correct: 1, explanation: 'Arrays are objects in JavaScript.' }, { id: 3, question: 'Number check?', options: ['number()', 'Number()', 'typeof', 'typeOf()'], correct: 2, explanation: 'Use typeof to check types.' }, { id: 4, question: '1 + "1" result?', options: ['2', '11', 'error', 'NaN'], correct: 1, explanation: 'JS coerces to string, result is 11.' }] },
  { title: 'SQL Fundamentals', category: 'Databases', difficulty: 'Beginner', duration: 40, badge: 'S', skills: ['SQL'], attempts: 13500, avgScore: 85, description: 'Test your SQL knowledge.', color: 'from-indigo-500 to-purple-500', questions: [{ id: 1, question: 'Select data keyword?', options: ['FETCH', 'SELECT', 'GET', 'RETRIEVE'], correct: 1, explanation: 'SELECT retrieves data.' }, { id: 2, question: 'Filter WHERE?', options: ['SELECT * WHERE age > 30', 'SELECT * FROM users WHERE age > 30', 'WHERE users age > 30', 'SELECT age > 30'], correct: 1, explanation: 'Use FROM then WHERE.' }, { id: 3, question: 'Remove duplicates?', options: ['UNIQUE', 'DISTINCT', 'REMOVE', 'DELETE'], correct: 1, explanation: 'DISTINCT removes duplicates.' }, { id: 4, question: 'Join tables?', options: ['SELECT t1 + t2', 'SELECT * FROM t1 JOIN t2 ON t1.id = t2.id', 'COMBINE t1, t2', 'MERGE'], correct: 1, explanation: 'Use JOIN to combine tables.' }] },
  { title: 'React Fundamentals', category: 'Frontend', difficulty: 'Intermediate', duration: 45, badge: 'R', skills: ['React', 'JavaScript'], attempts: 7800, avgScore: 76, description: 'Test your React knowledge.', color: 'from-cyan-500 to-blue-500', questions: [{ id: 1, question: 'JSX stands for?', options: ['JavaScript XML', 'Java Simple XML', 'JSON Extra', 'Extension'], correct: 0, explanation: 'JSX is JavaScript XML syntax.' }, { id: 2, question: 'Pass props?', options: ['<C props={d} />', '<C data />', 'C(d)', 'C.props = d'], correct: 0, explanation: 'Props are passed as attributes.' }, { id: 3, question: 'Replace componentDidMount?', options: ['useState', 'useEffect', 'useContext', 'useReducer'], correct: 1, explanation: 'useEffect replaces lifecycle hooks.' }, { id: 4, question: 'Hooks for memoization?', options: ['useMemo', 'useCallback', 'useRef', 'Both A and B'], correct: 3, explanation: 'Both useMemo and useCallback memoize.' }] },
  { title: 'AWS Basics', category: 'Cloud', difficulty: 'Beginner', duration: 50, badge: 'A', skills: ['AWS'], attempts: 16200, avgScore: 80, description: 'Test your AWS knowledge.', color: 'from-orange-500 to-yellow-500', questions: [{ id: 1, question: 'S3 stands for?', options: ['Service Storage', 'Storage Service', 'Simple Storage', 'Server Storage'], correct: 2, explanation: 'S3 = Simple Storage Service.' }, { id: 2, question: 'Availability Zone is?', options: ['region', 'data center', 'billing zone', 'security group'], correct: 1, explanation: 'AZ is a physical data center.' }, { id: 3, question: 'High availability needs?', options: ['One instance', 'Multiple AZs', 'RDS', 'VPC'], correct: 1, explanation: 'Spread across AZs for HA.' }, { id: 4, question: 'IAM stands for?', options: ['Inter Access', 'Identity Access', 'Internal Admin', 'Inter AWS'], correct: 1, explanation: 'IAM = Identity and Access Management.' }] },
  { title: 'Docker Basics', category: 'DevOps', difficulty: 'Intermediate', duration: 45, badge: 'D', skills: ['Docker', 'Containers'], attempts: 6500, avgScore: 81, description: 'Test your Docker knowledge.', color: 'from-blue-600 to-cyan-400', questions: [{ id: 1, question: 'Container is?', options: ['VM', 'Lightweight process', 'Storage', 'Protocol'], correct: 1, explanation: 'Containers are lightweight processes.' }, { id: 2, question: 'Dockerfile contains?', options: ['Configuration', 'Files', 'Security', 'Repository'], correct: 0, explanation: 'Dockerfile has build instructions.' }, { id: 3, question: 'Run container?', options: ['docker create', 'docker run', 'docker start', 'docker execute'], correct: 1, explanation: 'docker run creates and starts.' }, { id: 4, question: 'Image vs Container?', options: ['Same thing', 'Image is template, container is instance', 'Opposite', 'Related'], correct: 1, explanation: 'Image is a blueprint, container runs it.' }] },
  { title: 'Machine Learning Basics', category: 'AI/ML', difficulty: 'Intermediate', duration: 50, badge: 'M', skills: ['ML', 'Python'], attempts: 7200, avgScore: 74, description: 'Test ML knowledge.', color: 'from-purple-500 to-pink-500', questions: [{ id: 1, question: 'Supervised learning uses?', options: ['No labels', 'Labeled data', 'Unsupervised', 'Labels'], correct: 1, explanation: 'Supervised uses labeled data.' }, { id: 2, question: 'Overfitting means?', options: ['Too much data', 'Model memorizes training', 'Few features', 'Samples'], correct: 1, explanation: 'Overfitting = learning noise.' }, { id: 3, question: 'Data split ratio?', options: ['50-50', '70-30 or 80-20', 'All training', 'Random'], correct: 1, explanation: '70-30 or 80-20 train-test.' }, { id: 4, question: 'Cross-validation purpose?', options: ['Validate code', 'Better performance estimate', 'Validate data', 'Train faster'], correct: 1, explanation: 'Cross-validation estimates performance robustly.' }] },
  { title: 'System Design Basics', category: 'Architecture', difficulty: 'Advanced', duration: 60, badge: 'S', skills: ['Architecture', 'Scalability'], attempts: 4200, avgScore: 68, description: 'Test system design knowledge.', color: 'from-slate-600 to-gray-700', questions: [{ id: 1, question: 'Horizontal scaling is?', options: ['Add power to one', 'Add more servers', 'Increase RAM', 'Faster CPU'], correct: 1, explanation: 'Horizontal = more servers.' }, { id: 2, question: 'Eventual consistency?', options: ['Always consistent', 'Eventually consistent', 'Consistency check', 'Eventual backup'], correct: 1, explanation: 'Data eventually becomes consistent.' }, { id: 3, question: 'Load balancer does?', options: ['Balance weight', 'Distribute traffic', 'Balance code', 'DB tool'], correct: 1, explanation: 'Distributes requests across servers.' }, { id: 4, question: 'CAP theorem about?', options: ['Capacity', 'Consistency, Availability, Tolerance', 'Network', 'Data'], correct: 1, explanation: 'CAP = Consistency, Availability, Partition tolerance.' }] },
];

const importData = async () => {
  try {
    console.log('Connecting to database...');
    
    // Clear existing data
    await prisma.assessment.deleteMany();
    await prisma.course.deleteMany();
    await prisma.job.deleteMany();
    
    console.log('Inserting data...');
    await prisma.job.createMany({ data: jobs });
    console.log(`Inserted ${jobs.length} jobs`);
    
    await prisma.course.createMany({ data: courses });
    console.log(`Inserted ${courses.length} courses`);
    
    await prisma.assessment.createMany({ data: assessments });
    console.log(`Inserted ${assessments.length} assessments`);

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
};

importData();
